# Generated by Django 6.0.6 on 2026-07-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='interface',
            field=models.CharField(default='interface-a', max_length=20),
        ),
    ]
